// <auto-generated />
using BibliotecaMonolito;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaMonolito.Migrations;

[DbContext(typeof(LibraryDbContext))]
[Migration("20260805023836_Autor")]
partial class _20260805023836_Autor
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118");

        modelBuilder.Entity("BibliotecaMonolito.Models.Autor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Nacionalidad")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Autores");
            });

        modelBuilder.Entity("BibliotecaMonolito.Models.Libro", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("AnioPublicacion")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("AutorId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("AutorId");

                b.ToTable("Libros");
            });

        modelBuilder.Entity("BibliotecaMonolito.Models.Libro", b =>
            {
                b.HasOne("BibliotecaMonolito.Models.Autor", "Autor")
                    .WithMany()
                    .HasForeignKey("AutorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Autor");
            });
#pragma warning restore 612, 618
    }
}
