// <auto-generated />
using BibliotecaMonolito;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaMonolito.Migrations;

[DbContext(typeof(LibraryDbContext))]
partial class LibraryDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260805023836_Autor";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118");

        modelBuilder.Entity("BibliotecaMonolito.Models.Autor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Nacionalidad")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Autores");
            });

        modelBuilder.Entity("BibliotecaMonolito.Models.Libro", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("AnioPublicacion")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("AutorId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("AutorId");

                b.ToTable("Libros");
            });

        modelBuilder.Entity("BibliotecaMonolito.Models.Libro", b =>
            {
                b.HasOne("BibliotecaMonolito.Models.Autor", "Autor")
                    .WithMany()
                    .HasForeignKey("AutorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Autor");
            });
#pragma warning restore 612, 618
    }
}
